spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student?serverTimezone=UTC&useSSL=false&useTimezone=true&serverTimezone=Asia/Shanghai
    username: root
    password: Yq3139078
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  server:
    port: 8181
    address: localhost
#    port: ${port:9091}